[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
build_info = true
extra_output = ["storageLayout"]

[profile.openzeppelin-contracts-v4]
src = "src-v4"
remappings = [ "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts-v4" ]